name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
        cache: 'poetry'
    - run: poetry install --no-interaction --no-root

    - name: Run Unittest
      run: poetry run inv test

    - name: Run Lint
      run: poetry run inv lint