name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install poetry
        run: |
          curl -sSL curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Poetry Version
        run: |
          poetry --version
      - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction --no-root

  unittest:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Unittest
        run: poetry run python3 -m unittest discover tests

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lint
        run: |
          poetry run flake8 . --ignore=E203,W503 --max-line-length=88 --show-source --statistics
          poetry run mypy . --follow-imports=silent --ignore-missing-imports --show-column-numbers --no-pretty --warn-return-any --no-implicit-optional --disallow-untyped-calls --disallow-untyped-defs --allow-redefinition
          poetry run black . --check --diff --color